development:
  adapter: postgresql
  database: development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  database: test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  database: hollaback
  username: hollabackagain
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
