development:
  adapter: postgresql
  database: development
  host: localhost

test:
  adapter: postgresql
  database: test
  username: <username>
  password: <password>
  host: localhost

production:
  adapter: postgresql
  database: hollaback
  username: postgresql
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
